package signal

import (
	"syscall"
)

const (
	SIGRTMIN = 34
	SIGRTMAX = 64
)

// SignalMap is a map of Linux signals.
var SignalMap = map[string]syscall.Signal{
	"ABRT":        syscall.SIGABRT,
	"ALRM":        syscall.SIGALRM,
	"BUS":         syscall.SIGBUS,
	"CHLD":        syscall.SIGCHLD,
	"CLD":         syscall.SIGCLD,
	"CONT":        syscall.SIGCONT,
	"FPE":         syscall.SIGFPE,
	"HUP":         syscall.SIGHUP,
	"ILL":         syscall.SIGILL,
	"INT":         syscall.SIGINT,
	"IO":          syscall.SIGIO,
	"IOT":         syscall.SIGIOT,
	"KILL":        syscall.SIGKILL,
	"PIPE":        syscall.SIGPIPE,
	"POLL":        syscall.SIGPOLL,
	"PROF":        syscall.SIGPROF,
	"PWR":         syscall.SIGPWR,
	"QUIT":        syscall.SIGQUIT,
	"SEGV":        syscall.SIGSEGV,
	"STKFLT":      syscall.SIGSTKFLT,
	"STOP":        syscall.SIGSTOP,
	"SYS":         syscall.SIGSYS,
	"TERM":        syscall.SIGTERM,
	"TRAP":        syscall.SIGTRAP,
	"TSTP":        syscall.SIGTSTP,
	"TTIN":        syscall.SIGTTIN,
	"TTOU":        syscall.SIGTTOU,
	"UNUSED":      syscall.SIGUNUSED,
	"URG":         syscall.SIGURG,
	"USR1":        syscall.SIGUSR1,
	"USR2":        syscall.SIGUSR2,
	"VTALRM":      syscall.SIGVTALRM,
	"WINCH":       syscall.SIGWINCH,
	"XCPU":        syscall.SIGXCPU,
	"XFSZ":        syscall.SIGXFSZ,
	"RTMIN":       SIGRTMIN,
	"RTMIN+1":     SIGRTMIN + 1,
	"RTMIN+2":     SIGRTMIN + 2,
	"RTMIN+3":     SIGRTMIN + 3,
	"RTMIN+4":     SIGRTMIN + 4,
	"RTMIN+5":     SIGRTMIN + 5,
	"RTMIN+6":     SIGRTMIN + 6,
	"RTMIN+7":     SIGRTMIN + 7,
	"RTMIN+8":     SIGRTMIN + 8,
	"RTMIN+9":     SIGRTMIN + 9,
	"RTMIN+10":    SIGRTMIN + 10,
	"RTMIN+11":    SIGRTMIN + 11,
	"RTMIN+12":    SIGRTMIN + 12,
	"RTMIN+13":    SIGRTMIN + 13,
	"RTMIN+14":    SIGRTMIN + 14,
	"RTMIN+15":    SIGRTMIN + 15,
	"SIGRTMAX-14": SIGRTMAX - 14,
	"SIGRTMAX-13": SIGRTMAX - 13,
	"SIGRTMAX-12": SIGRTMAX - 12,
	"SIGRTMAX-11": SIGRTMAX - 11,
	"SIGRTMAX-10": SIGRTMAX - 10,
	"SIGRTMAX-9":  SIGRTMAX - 9,
	"SIGRTMAX-8":  SIGRTMAX - 8,
	"SIGRTMAX-7":  SIGRTMAX - 7,
	"SIGRTMAX-6":  SIGRTMAX - 6,
	"SIGRTMAX-5":  SIGRTMAX - 5,
	"SIGRTMAX-4":  SIGRTMAX - 4,
	"SIGRTMAX-3":  SIGRTMAX - 3,
	"SIGRTMAX-2":  SIGRTMAX - 2,
	"SIGRTMAX-1":  SIGRTMAX - 1,
	"SIGRTMAX":    SIGRTMAX,
}
